### ISSUE TITLE
Horizontal scrollbar covering UI

### ISSUE THREAD

**Issue by moremeatlessfat** [Flamenco/grav-plugin-editor#3]
Hi,

I love this plugin for Grav where it allows you to edit the source files directly.

But in Chrome, there's a bug where the horizontal scrollbar is set at 100% height, so none of the file links are clickable.

![image](https://user-images.githubusercontent.com/8219962/40291008-6a55a6c0-5d05-11e8-9f31-dd6e3dc32fb6.png)

Can you, please, look into it?

Thanks,
Sharlene

**Comment by moremeatlessfat** [comment]
Sorry, please delete, this is a duplicate of the previous issue raised.

**Comment by Flamenco** [comment]
See https://github.com/Flamenco/grav-plugin-editor/issues/2
