### ISSUE TITLE
Save does not function, permissions checked

### ISSUE THREAD

**Issue by mvhconsult** [Flamenco/grav-plugin-editor#5]
Weird issue: save does not work, neither copy. Permissions are correct on the files. Is there some way to see the errors?

**Comment by Flamenco** [comment]
Hello @mvhconsult,

1.  Are there any errors reported in the 'toast' popup?
2.  Has saving ever worked for you? (Is this a regression)?
3.  Have you checked the grav log?

**Comment by Flamenco** [comment]
We have found the issue and will patch it in the next couple of hours.  Thanks for reporting.

**Comment by Flamenco** [comment]
https://github.com/Flamenco/grav-plugin-editor/releases/tag/0.1.8

This was related to a regular expression that was not cross browser compatible.  Specifically, only Chrome supports negative lookbehind expressions.

**Comment by mvhconsult** [comment]
Thank. For my info: what is the toast popup?

**Comment by mvhconsult** [comment]
Updated, and works very well. May close.

**Comment by Flamenco** [comment]
The toast popup is the ‘your file was saved’ message.

**Comment by mvhconsult** [comment]
Ah, well, that was not showing, but is now. Thanks.
